linux (Allwinner): new patch required for 6.11-rc7
6.11-rc7 has refactored drm https://github.com/torvalds/linux/commit/9da7ec9b19d8c1ad4f44e459fa5f93ad7a117dcd
resulting in the following compile error.

build.LibreELEC-H6.aarch64-13.0-devel/toolchain/bin/aarch64-libreelec-linux-gnu-ld: drivers/gpu/drm/sun4i/sun8i_dw_hdmi.o: in function `sun8i_dw_hdmi_bind':
build.LibreELEC-H6.aarch64-13.0-devel/build/linux-6.11-rc7/drivers/gpu/drm/sun4i/sun8i_dw_hdmi.c:394:(.text+0x73c): undefined reference to `drm_bridge_connector_init'